sudo: required
language: php

php:
- 5.6
- 7.1

git:
  depth: 1

services:
- docker

env:
  global:
  - DOCKER_COMPOSE_VERSION=1.17.1
  matrix:
  - DRUPAL_VERSION=~8.5
  - DRUPAL_VERSION=~8.6@rc
  - DRUPAL_VERSION=8.7.x-dev

matrix:
  allow_failures:
  - env: DRUPAL_VERSION=8.7.x-dev

before_install:
- cp docker-compose.yml.dist docker-compose.yml
- docker-compose up -d

install:
- docker-compose exec -u root php composer require webflo/drupal-core-require-dev:$DRUPAL_VERSION --dev
- docker-compose exec -u root php chown -R www-data:www-data build

before_script:
- docker-compose exec -u www-data php ./vendor/bin/run drupal:site-install

script:
- docker-compose exec -u www-data php ./vendor/bin/grumphp run
- docker-compose exec -u www-data php ./vendor/bin/phpunit
- docker-compose exec -u www-data php ./vendor/bin/behat

notifications:
  email: false