sudo: required

services:
  - docker
  - docker-compose

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.17.1
  matrix:
    - DRUPAL_VERSION=8.3.x-dev
    - DRUPAL_VERSION=8.4.x-dev
    - DRUPAL_VERSION=8.5.x-dev

before_install:
  - docker-compose up -d
  - docker ps

install:
  - docker-compose exec -u root php composer require drupal/core:$DRUPAL_VERSION --dev --prefer-dist

before_script:
  - docker-compose exec -u root php ./vendor/bin/run drupal:site-setup
  - docker-compose exec -u root php ./vendor/bin/run drupal:site-install

script:
  - docker-compose exec -u root php ./vendor/bin/grumphp run
  - docker-compose exec -u root php ./vendor/bin/phpunit
  - docker-compose exec -u root php ./vendor/bin/behat

notifications:
  email: false